### ISSUE TITLE
read(io, InlineString3) etc doesn't work

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/WeakRefStrings.jl#81]
Consider:

```julia
julia> using WeakRefStrings

julia> a = InlineString("ABC")
"ABC"

julia> buf2 = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(buf2, a)
3

julia> seekstart(buf2)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=3, maxsize=Inf, ptr=1, mark=-1)

julia> read(buf2, InlineString3)
ERROR: The IO stream does not support reading objects of type InlineString3.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] read(s::IOBuffer, T::Type)
   @ Base ./io.jl:967
 [3] top-level scope
   @ REPL[10]:1
   ```
   
This seems like is should be straight forward to add.

Having that may allow to not need the code that was added in #78 
since `deserialize` calls  `read`

**Comment by quinnj** [comment]
Hmmmm, I'm not quite sure how this should all work. Part of the problem right now is that when you call `write(buf2, a)`, we're writing the string out as a "string"; i.e. transforming from the inlinestring bit representation to individual `Char`s, then writing those out (hence the `3` when writing it out). But then that makes calling `read` awkward; should it read 3 bytes? what if the `InlineString3` only had a length of 2? It seems like there's no way to know to properly read an `InlineString3` since we don't know how long it's supposed to be.

On the other hand, we could change `write` to write the 4-byte bit representation of `InlineString3`, which then makes reading it back in straightforward. And this would also work well for `serialize`/`deserialize`.

The only hangup is that `write`ing the bit representation will certainly be weird for users who are just using these like "strings" and want to write out the characters.

cc: @bkamins

**Comment by oxinabox** [comment]
> using these like "strings" and want to write out the characters.

Shouldn't they be using `print`?

**Comment by bkamins** [comment]
`write`:
> Write the canonical binary representation of a value to the given I/O streamor file.

`read`:
> Read a single value of type `T` from `io`, in canonical binary representation.

So we just need to decide what a "canonical binary representation" of `InlineString*` is and I assume it should be just the raw bytes the given type consists of. This will ensure that storing/reading `InlineString*` in binary format (cannonical representation) can be performed very fast as you have a fixed offset (like in data bases when you have `CHAR`), which I think is a desired feature.

Actually I think that:
```
read(s::IO, ::Type{String}) = String(read(s))
```
in Julia Base is slightly problematic given the contract above (but I understand its rationale and usefulness).

What I would recommend is to go along what @oxinabox recommends but clearly document `read` and `write` for `InlineString*` along with its canonical representation.

CC @StefanKarpinski regarding the contract for `read`/`write` of strings in Julia Base.
